services:
  spark-master:
    build: .
    image: custom-spark-image
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"  # Spark Master UI
      - "7077:7077"  # Spark Master RPC
    volumes:
      - ./apps:/opt/bitnami/spark/workspace/apps
      - ./data:/opt/bitnami/spark/workspace/data
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no

  spark-worker-1:
    build: .
    image: custom-spark-image
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"  # Spark Worker 1 UI
    volumes:
      - ./apps:/opt/bitnami/spark/workspace/apps
      - ./data:/opt/bitnami/spark/workspace/data
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=4G
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no

  spark-worker-2:
    build: .
    image: custom-spark-image
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"  # Spark Worker 2 UI
    volumes:
      - ./apps:/opt/bitnami/spark/workspace/apps
      - ./data:/opt/bitnami/spark/workspace/data
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=4G
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no

  jupyterlab:
    build: .
    image: custom-spark-image
    container_name: jupyterlab
    hostname: jupyterlab
    depends_on:
      - spark-master
    ports:
      - "8888:8888" # JupyterLab UI
      - "4040:4040" # Spark UI for Jupyter
    volumes:
      - ./notebooks:/opt/bitnami/spark/workspace/notebooks
      - ./data:/opt/bitnami/spark/workspace/data
      - ./apps:/opt/bitnami/spark/workspace/apps
    environment:
      - SPARK_MODE=client
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    command: >
      sleep infinity